### ISSUE TITLE
list関連以外のAPIについて

### ISSUE THREAD

**Issue by Goryudyuma** [bgpat/twtr#6]
users/showやfollowers/idsとかほしい

(list操作以外の)何例か書いてくれたら、後はこっちでほしいメソッド書いてプルリク送ります。

**Comment by bgpat** [comment]
👀

**Comment by bgpat** [comment]
`users/*` のAPIについて実装しました。
`nil`は拾いたいので基本的にポインタで返す、`slice`とか`map`はそのまま返してます。
こうした方がいいみたいなのがあれば意見ください。

**Comment by bgpat** [comment]
一旦閉じます
